# Generated by Django 5.1.7 on 2025-03-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('travel', 'Travel'), ('food', 'Food'), ('lifestyle', 'Lifestyle'), ('personal', 'Personal'), ('others', 'Others')], default='personal', max_length=20),
        ),
    ]
